services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: dizzzyy123
      POSTGRES_DB: jsonparserdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d jsonparserdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: dizzzyy123
      POSTGRES_DB: jsonparserdb
      POSTGRES_HOST: postgres
    volumes:
      - ./data:/app/data
    mem_limit: 100m

volumes:
  pgdata: